myapp/urls.py
from django.urls import path
import imp
from .views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

mysite/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("myapp.urls", "myapp"), namespace="myapp")),
]

myapp/models.py
from operator import mod
from platform import mac_ver
from pyexpat import model
from django.db import models

# Create your models here.
class Data(models.Model):
    domain = models.CharField(max_length=200)
    api = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.domain}"

myapp/views.py
import imp
from multiprocessing import context
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.views.generic import View
from .models import Data
import requests
from requests.auth import HTTPBasicAuth


# Create your views here.
class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "home.html")

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            username = request.POST["username"]
            password = request.POST["password"]
            if Data.objects.all()[:1].get():
                get_data = Data.objects.all()[:1].get()
                url = get_data.domain + get_data.api
                print(url)
                response = requests.get(
                    url, auth=HTTPBasicAuth(username=username, password=password)
                )
                print(response)
                if response.status_code == 200:
                    context = {"status_code": response.status_code}
                    return render(request, "filepicker.html", context=context)
                else:
                    context = {"msg": "Please provide valid credentials"}
                    return render(request, "home.html", context=context)
            else:
                return render(request, "home.html")

templates/filepicker.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Gurdeep singh osahan">
    <meta name="author" content="Gurdeep singh osahan">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <div class="row justify-content-center" style="margin-top:145px">
        <div class="col-6 align-self-center">
            <form action="" method="POST" class="m-4">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">Choose a FILE</label>
                    <input type="file" class="form-control" id="exampleInputEmail1" aria-describedby="file" name="file">
                </div>
                <div class="alert alert-success" role="alert">
                    {{ status_code }}
                </div>
                <button type="submit" class="btn btn-primary mt-2 w-100">Submit</button>
            </form>
        </div>
    </div>
</body>

</html>

templates/home.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Gurdeep singh osahan">
    <meta name="author" content="Gurdeep singh osahan">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <div class="row justify-content-center" style="margin-top:145px">
        <div class="col-6 align-self-center">

            <form action="{% url 'myapp:home' %}" method="POST">
                {% if msg %}
                <div class="alert alert-danger" role="alert">
                    {{msg}}
                </div>
                {% endif %}
                {% csrf_token %}

                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="UsernameHelp"
                        placeholder="Enter username" name="username">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"
                        name="password">
                </div>

                <button type="submit" class="btn btn-primary mt-4 w-100">Submit</button>
            </form>
        </div>
    </div>

</body>

</html>